#!/bin/bash

send_status_update() {
    curl -X 'POST' \
      'http://<deine-ipadresse-zu-deinem-gamserver-verwaltungs-api>:8000/update/' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d "{
    \"message\": \"$1\",
    \"timestamp\": \"$(date -Iseconds)\"
    }"
}

cd /minecraft
send_status_update "Minecraft-Server wird gestartet"
exec java -Xms1G -Xmx1G -jar spigot.jar nogui # hir Gb an ramm einstellen
send_status_update "Minecraft-Server wurde gestartet"
